title: "IHS新卒・中途採用サイト"
baseurl: "/recruit"
url: "http://www.iimhs.co.jp"
port: 3000

source: "src"
destination: "dest"

exclude:
  - Gemfile
  - Gemfile.lock
  - admin
  - template.html
  - _includes
  - _layout
  - _plugin
  - node_modules
  - package.json
  - gulpfile.js
  - .csslintrc.json
  - .htmlhintrc.json
  - .jekyll-metadata

# Build settings
markdown: kramdown
